### ISSUE TITLE
Vector and Heap library licenses

### ISSUE THREAD

**Issue by UlfTheFirst** [GlorifiedPig/Luafinding#6]
Hi, I was interested in LuaFinding and I wanted to incoporate it into my game. However I was not able to find licenses for the libraries you use in your project. I was able to find a vector-library (https://github.com/automattf/vector.lua) which seems similar to yours and I would exchange the library with the one I found, because it has a proper license. What about the heap library? Do you know a similar library I can interchange it with? Did you base your heap.lua on annother library? Are there any attributions I need to keep in mind when I use LuaFinding (I except attributing you)?

**Comment by UlfTheFirst** [comment]
Is your heap implementation based on the roblox one (https://github.com/Roblox/Wiki-Lua-Libraries/blob/master/StandardLibraries/Heap.lua)???

**Comment by GlorifiedPig** [comment]
No attributions, feel free to use anything in this for whatever you want
